const Itemdata = [
    {
        id: '1',
        price: '$10',
        name: 'Egg and Salad',
        description: 'Try this mouthwatering dish',
        category: 'Breakfast',
        img: ['https://i.ibb.co/kQtBt2L/breakfast1.png'],
    },
    {
        id: '2',
        price: '$20',
        name: 'Salad and Bacon',
        description: 'Try this mouthwatering dish',
        category: 'Breakfast',
        img: ['https://i.ibb.co/8bJV04d/breakfast2.png'],
    },
    {
        id: '3',
        price: '$30',
        name: 'Egg and Bread',
        description: 'Try this mouthwatering dish',
        category: 'Breakfast',
        img: ['https://i.ibb.co/xjkVyVZ/breakfast3.png'],
    },
    {
        id: '4',
        price: '$40',
        name: 'Tomato Bread',
        description: 'Try this mouthwatering dish',
        category: 'Breakfast',
        img: ['https://i.ibb.co/GPS1MS0/breakfast4.png'],
    },
    {
        id: '5',
        price: '$50',
        name: 'Fruit and Egg',
        description: 'Try this mouthwatering dish',
        category: 'Breakfast',
        img: ['https://i.ibb.co/brDv96s/breakfast5.png'],
    },
    {
        id: '6',
        price: '$60',
        name: 'Tomato Bacon',
        description: 'Try this mouthwatering dish',
        category: 'Breakfast',
        img: ['https://i.ibb.co/WfVDMQ2/breakfast6.png'],
    },
    {
        id: '7',
        category: 'Lunch',
        name: 'Steak Tomatoes',
        price: '$21',
        img: ['https://i.ibb.co/F7CKNrj/lunch1.png'],
    },
    {
        id: '8',
        category: 'Lunch',
        name: 'Salmon Delight',
        price: '$22',
        img: ['https://i.ibb.co/zGTrGFw/lunch2.png'],
    },
    {
        id: '9',
        category: 'Lunch',
        name: 'Fish Fry',
        price: '$23',
        img: ['https://i.ibb.co/prFCj77/lunch3.png'],
    },
    {
        id: '10',
        category: 'Lunch',
        name: 'Chicken Chap',
        price: '$24',
        img: ['https://i.ibb.co/pX701Bg/lunch4.png'],
    },
    {
        id: '11',
        category: 'Lunch',
        name: 'Fried chicken',
        price: '$25',
        img: ['https://i.ibb.co/f85H3vz/lunch5.png'],
    },
    {
        id: '12',
        category: 'Lunch',
        name: 'Dressing Salad',
        price: '$26',
        img: ['https://i.ibb.co/Vpf4qPW/lunch6.png'],
    },
    {
        id: '13',
        category: 'Dinner',
        name: 'Keto Salad',
        price: '$31',
        img: ['https://i.ibb.co/BsmW04m/dinner1.png'],
    },
    {
        id: '14',
        category: 'Dinner',
        name: 'Fish Cutlet',
        price: '$32',
        img: ['https://i.ibb.co/85FdR1G/dinner2.png'],
    },
    {
        id: '15',
        category: 'Dinner',
        name: 'Baked Chicken',
        price: '$33',
        img: ['https://i.ibb.co/7CNNcX6/dinner3.png'],
    },
    {
        id: '16',
        category: 'Pasta ',
        name: 'Diet Salad',
        price: '$34',
        img: ['https://i.ibb.co/JB1JctT/dinner4.png'],
    },
    {
        id: '17',
        category: 'Chicken Salad',
        name: 'Keto Salad',
        price: '$35',
        img: ['https://i.ibb.co/CBYXsWr/dinner5.png'],
    },
    {
        id: '18',
        category: 'Dinner',
        name: 'Fish Delight',
        price: '$36',
        img: ['https://i.ibb.co/KV78f0v/dinner6.png'],
    },
];

export default Itemdata;
